version: '3.7'

services:
  mongo:
    container_name: mongo-simple-proman
    restart: always
    image: bitnami/mongodb:latest
    environment:
      - MONGODB_ROOT_PASSWORD=root
      - MONGODB_USERNAME=mongouser
      - MONGODB_PASSWORD=secret
      - MONGODB_DATABASE=simple-proman
    volumes:
      - mongodb-simple-proman:/bitnami/mongodb
    ports:
      - 27017:27017

volumes:
  mongodb-simple-proman: